### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by Dannemann** [eyscode/timetracker#11]
I'm getting the attached error while running `tt show`.
The same thing happens if I try `tt show -w` and variants.
I have not tried to load any hours yet.

I am using a MacOS machine and I installed Python 3.9 (the latest version from today). I installed tt with pip3.

![Screen Shot 2021-03-30 at 16 26 23](https://user-images.githubusercontent.com/1202583/113045325-171e6080-9175-11eb-8534-638fbe0a8988.png)

**Comment by fboaventura** [comment]
Hi @Dannemann !

Did you set your `~/.timetracker/config.toml` properly?

The names for the options have to match exactly as they are on TimeTracker:

```toml
[options]
project = 'Springfield Nuclear Power Plant'
assignment = 'Nuclear Safety Inspection'
focal = 'Mr. Burns'
```

Cheers,
